# Generated by Django 4.0.3 on 2022-03-10 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("offeror_point_start", models.PositiveSmallIntegerField()),
                ("offeror_point_end", models.PositiveSmallIntegerField()),
                ("acceptor_point_start", models.PositiveSmallIntegerField()),
                ("acceptor_point_end", models.PositiveSmallIntegerField()),
                (
                    "accept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="battle.accept",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="NTF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=240)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=240)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ntf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="battle.ntf",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "offeror_choice",
                    models.SmallIntegerField(
                        choices=[(1, "Paper"), (2, "Stone"), (3, "Scissors")]
                    ),
                ),
                (
                    "acceptor_choice",
                    models.SmallIntegerField(
                        choices=[(1, "Paper"), (2, "Stone"), (3, "Scissors")]
                    ),
                ),
                ("offeror_minus_point", models.SmallIntegerField()),
                ("acceptor_minus_point", models.SmallIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="battle.battle",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="battle.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=240)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="battle.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="accept",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="battle.offer"
            ),
        ),
        migrations.AddField(
            model_name="accept",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="battle.user"
            ),
        ),
    ]
