# Generated by Django 4.0.3 on 2022-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="number",
            field=models.SmallIntegerField(default=0),
        ),
    ]
