# Generated by Django 4.0.3 on 2022-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0002_round_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="number",
            field=models.SmallIntegerField(),
        ),
    ]
