# Generated by Django 4.0.3 on 2022-03-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_alter_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='battle.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='acceptor_choice',
            field=models.SmallIntegerField(choices=[(1, 'Paper'), (2, 'Scissors'), (3, 'Stone')]),
        ),
        migrations.AlterField(
            model_name='round',
            name='offeror_choice',
            field=models.SmallIntegerField(choices=[(1, 'Paper'), (2, 'Scissors'), (3, 'Stone')]),
        ),
    ]
