# Generated by Django 4.0.3 on 2022-03-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_alter_battle_winner_alter_round_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='acceptor_websocket',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='offeror_websocket',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
