# Generated by Django 4.0.3 on 2022-03-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_round_acceptor_websocket_round_offeror_websocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='acceptor_choice',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Paper'), (2, 'Scissors'), (3, 'Stone')], null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='offeror_choice',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Paper'), (2, 'Scissors'), (3, 'Stone')], null=True),
        ),
    ]
