# Generated by Django 4.0.3 on 2022-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_alter_round_acceptor_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='acceptor_minus_point',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='offeror_minus_point',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
